---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: search-engine
    component: mongodb
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongodb
      labels:
        app: search-engine
        component: mongodb
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: mongodb
        ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: mongodb
            protocol: TCP
        volumeMounts:
          - name: {{ .Values.volumeMounts.name }}
            mountPath: {{ .Values.volumeMounts.mountPath }}
      volumes:
      - name: {{ .Values.volumeMounts.name }}
        persistentVolumeClaim:
          claimName: {{ template "mongodb.fullname" . }}
