apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mongodb.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ template "mongodb.fullname" . }}
  resources:
    requests:
      storage: 4Gi
